### ISSUE TITLE
support another sofpal pac archive?

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/UnisonShiftManager#1]
same as i asked long time ago on garbro
https://github.com/morkt/GARbro/issues/56

**Comment by marcussacana** [comment]
So... the name of this engine is softpal? Srry i have no idea this is the first game who i found with this engine...

**Comment by 0xh3LL0** [comment]
according to [this](https://morkt.github.io/GARbro/supported.html), yes...
<a href="https://imgur.com/a5S8oCM"><img src="https://i.imgur.com/a5S8oCM.png" title="source: imgur.com" /></a>

**Comment by 0xh3LL0** [comment]
tested, it works!
