### ISSUE TITLE
support for this game please

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/UnisonShiftManager#2]
i just notice that you add script support...
this script from the game i test with unipac earlier, however i found something odd...
the text.dat extracted from your unipac is different from garbro, so i attach them both,
maybe you can take a look?
[text.zip](https://drive.google.com/file/d/1MO89CTlyfChULtao1w_fSR9g0zTNYrSx/view?usp=sharing)

**Comment by marcussacana** [comment]
Fixed, The file isn't the same because the GarBro decrypt while extracting the file, I don't think the encryption is a part of the .pac archive because we have decrypted files like the .txt, and the .dat header is decrypted, Because this to me looks more Rigth the Script Editor decrypt the file.

**Comment by 0xh3LL0** [comment]
okay, so dump and insert is working, but is this normal? 
seem like english and japanese cant be used together...
how about your leyline? can it use english and japanese?
<a href="https://imgur.com/Yx9hlrN"><img src="https://i.imgur.com/Yx9hlrN.png" title="source: imgur.com" /></a>

**Comment by marcussacana** [comment]
you have sure this crash caused by my tool? this script format is really easy 
![https://a.safe.moe/cy07g.png](https://a.safe.moe/cy07g.png)
Just the "ID" after the string with null termination nothing more...
Is more probabbly is a problem of the repacker?... 
Take a look if is allways crash or just a random crash

---
about if can use eng & jap, Srry, what you want ask with this? if can put the game bi-lang?

**Comment by 0xh3LL0** [comment]
> you have sure this crash caused by my tool?

um, no, i don't think so...

> Take a look if is allways crash or just a random crash
about if can use eng & jap, Srry, what you want ask with this? if can put the game bi-lang?

i think here is the problem...
softpal can not use english and japanese at the same time,
here is how i produce the error:
- i translate 1 line to english to test, as usual, i type THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG
- insert the text.txt to text.dat,
- pack it to pac
- launch the game, it works
- click the game screen, normally it should give me the next text, but its not, it gave me an error instead...

summary it crash when it change from english text to japanese text,
so thats why i'm asking you, if leyline has the same problem or not, since it use the same engine?
and i'm talking about editing the script with this tools, not your string reloads, since i'm sure there is no problem with that...

**Comment by marcussacana** [comment]
I only have the english version here, srry...
But if i put japanese character into the script work without problem...

**Comment by 0xh3LL0** [comment]
hm... leyline have no problem, eh...
then, the problem mostly is the game it self :( 

guess you can close this issue

**Comment by 0xh3LL0** [comment]
just want to let you know, issue for this game has been resolved
just in case you want to take a look, and maybe fix yours as well :) 
https://github.com/Yggdrasill-Moe/Niflheim/issues/2

**Comment by marcussacana** [comment]
I see... have external offsets... well, I don't noticed since I just played using the stringreloads...
Well, no idea if it's better update my tool, if already have the tool of this guy it's lost of time to me update it.
