### ISSUE TITLE
Error converting from UTF-8

### ISSUE THREAD

**Issue by Cerzs** [marcussacana/UnisonShiftManager#3]
Hi again, @marcussacana!

I have a problem with The Witch's Love Diary. I modified the font so I can use symbols instead of accented characters, I used tiny katakana (ｧｪｨｫｩﾃ), but when repacking, in-game I see this:

[Link](https://i.imgur.com/JdB5UWm.jpg)

Do you know if that's a problem with the tool or with the engine?

Edit: I also noticed that if the line is larger than original, the game crashes. Is there a fix for this?

**Comment by marcussacana** [comment]
No, this tool is basically 'incomplete' and need a manually offset updating to work with the game, I really don't will fix this because I can just use the SRL to skip the disassembly of the script engine, this game is in my to-do list then just wait a time.

**Comment by Cerzs** [comment]
I see, I'll be checking the SRL repository, then! Thanks.

**Comment by marcussacana** [comment]
Game Added @Cerzs
